sudo: false
language: perl
perl:
   - '5.24'
   - '5.22'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
matrix:
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla App::cpm
   - cpm install -g $(dzil authordeps --missing | grep -vP '[^\\w:]')
   - cpm install -v -g $(dzil listdeps --author --missing | grep -vP '[^\\w:]')

script:
   - dzil smoke --release --author
